# Nom du workflow
name: Build and Attach Release Firmware

# Déclencheur : s'exécute quand une "Release" est publiée
on:
  release:
    types: [published]
  # Ajout du déclencheur manuel pour plus de flexibilité
  workflow_dispatch:

# Tâches à exécuter
jobs:
  # =======================================================
  # JOB 1: Compiler la Passerelle (Gateway)
  # =======================================================
  build-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v3
        with:
          path: ~/.platformio/
          key: ${{ runner.os }}-pio

      - name: Set up PlatformIO Core
        # === CORRECTION APPLIQUÉE ICI ===
        uses: platformio/action-core@v3

      - name: Build Gateway Firmware
        working-directory: ./gateway
        run: pio run

      - name: Prepare Gateway Firmware File
        run: |
          RELEASE_TAG="${{ github.ref_name }}"
          mv ./gateway/.pio/build/heltec_wifi_lora_32_v3/firmware.bin "Gateway-Firmware-${RELEASE_TAG}.bin"

      - name: Upload Gateway Firmware to Release
        uses: softprops/action-gh-release@v1
        with:
          files: Gateway-Firmware-*.bin

  # =======================================================
  # JOB 2: Compiler le module AquaReservPro
  # =======================================================
  build-aquareserv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Cache PlatformIO dependencies
        uses: actions/cache@v3
        with:
          path: ~/.platformio/
          key: ${{ runner.os }}-pio
      - name: Set up PlatformIO Core
        # === CORRECTION APPLIQUÉE ICI ===
        uses: platformio/action-core@v3

      - name: Build AquaReservPro Firmware
        working-directory: ./modules/AquaReservPro
        run: pio run

      - name: Prepare AquaReservPro Firmware File
        run: |
          RELEASE_TAG="${{ github.ref_name }}"
          mv ./modules/AquaReservPro/.pio/build/heltec_wifi_lora_32_v3/firmware.bin "AquaReservPro-Firmware-${RELEASE_TAG}.bin"

      - name: Upload AquaReservPro Firmware to Release
        uses: softprops/action-gh-release@v1
        with:
          files: AquaReservPro-Firmware-*.bin

  # =======================================================
  # JOB 3: Compiler le module WellguardPro
  # =======================================================
  build-wellguard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Cache PlatformIO dependencies
        uses: actions/cache@v3
        with:
          path: ~/.platformio/
          key: ${{ runner.os }}-pio
      - name: Set up PlatformIO Core
        # === CORRECTION APPLIQUÉE ICI ===
        uses: platformio/action-core@v3

      - name: Build WellguardPro Firmware
        working-directory: ./modules/WellguardPro
        run: pio run

      - name: Prepare WellguardPro Firmware File
        run: |
          RELEASE_TAG="${{ github.ref_name }}"
          mv ./modules/WellguardPro/.pio/build/heltec_wifi_lora_32_v3/firmware.bin "WellguardPro-Firmware-${RELEASE_TAG}.bin"

      - name: Upload WellguardPro Firmware to Release
        uses: softprops/action-gh-release@v1
        with:
          files: WellguardPro-Firmware-*.bin
